** Linear Algebra **
Linear Algebra is a branch of mathematics that deals with vectors and matrices. It is used in various fields such as machine learning, computer graphics, cryptography, and engineering. In this notebook, we will discuss some basic concepts of linear algebra and how to implement them in Python.


What is a vector
A vector is a quantity that has both magnitude and direction. It is represented by an arrow in space. In linear algebra, a vector is represented as an array of numbers. For example, the vector v = [1, 2, 3] has three components and is represented as a column vector:

In [1]:
v = [3, 2]
print(v)

[3, 2]


In [2]:
import numpy as np
v = np.array([3, 2])
print(v)

[3 2]


In [3]:
import numpy as np
v = np.array([4, 1, 2])
print(v)

[4 1 2]


In [4]:
import numpy as np
v = np.array([6, 1, 5, 8, 3])
print(v)

[6 1 5 8 3]


Adding and combining vectors
Vectors can be added together by adding their corresponding components. For example, if v = [1, 2, 3] and w = [4, 5, 6], then the sum of v and w is [1+4, 2+5, 3+6] = [5, 7, 9]. We can also combine vectors by concatenating their components. For example, if v = [1, 2, 3] and w = [4, 5, 6], then the combination of v and w is [1, 2, 3, 4, 5, 6].

In [5]:
from numpy import array
v = array([3,2])
w = array([2,-1])
# sum the vectors
v_plus_w = v + w
# display summed vector
print(v_plus_w) # [5, 1]

[5 1]


Scalar Vectors
A scalar is a single number that can be multiplied by a vector to produce a new vector. For example, if v = [1, 2, 3] and s = 2, then the product of s and v is [2*1, 2*2, 2*3] = [2, 4, 6].

Span and linear dependence
The span of a set of vectors is the set of all possible linear combinations of those vectors. If the span of a set of vectors is the entire space, then the vectors are said to be linearly independent. If the span of a set of vectors is less than the entire space, then the vectors are said to be linearly dependent.

Linear Transformations
A linear transformation is a function that maps vectors from one space to another while preserving the vector addition and scalar multiplication properties. For example, a rotation or reflection of a vector is a linear transformation.

Basis Vectors
A basis is a set of linearly independent vectors that span a space. The basis vectors are the vectors that form the basis of the space. For example, the standard basis for a 2D space is the vectors [1, 0] and [0, 1].

Matrix Vector Multiplication
A matrix is a rectangular array of numbers. A matrix can be multiplied by a vector to produce a new vector. For example, if A is a matrix and v is a vector, then the product of A and v is a new vector w = Av.

In [8]:
from numpy import array
# compose basis matrix with i-hat and j-hat
basis = array(
[[3, 0],
[0, 2]]
)
# declare vector v
v = array([1,1])
# create new vector
# by transforming v with dot product
new_v = basis.dot(v)
print(new_v) # [3, 2]

[3 2]


In [6]:
from numpy import array
# Declare i-hat and j-hat
i_hat = array([2, 0])
j_hat = array([0, 3])
# compose basis matrix using i-hat and j-hat
# also need to transpose rows into columns
basis = array([i_hat, j_hat]).transpose()
# declare vector v
v = array([1,1])
# create new vector
# by transforming v with dot product
new_v = basis.dot(v)
print(new_v) # [2, 3]

[2 3]


In [7]:
from numpy import array
# Declare i-hat and j-hat
i_hat = array([2, 0])
j_hat = array([0, 3])
# compose basis matrix using i-hat and j-hat
# also need to transpose rows into columns
basis = array([i_hat, j_hat]).transpose()
# declare vector v 0
v = array([2,1])
# create new vector
# by transforming v with dot product
new_v = basis.dot(v)
print(new_v) # [4, 3]

[4 3]


In [ ]:
from numpy import array
# Declare i-hat and j-hat
i_hat = array([2, 3])
j_hat = array([2, -1])
# compose basis matrix using i-hat and j-hat
# also need to transpose rows into columns
basis = array([i_hat, j_hat]).transpose()
# declare vector v 0
v = array([2,1])
# create new vector
# by transforming v with dot product
new_v = basis.dot(v)
print(new_v) # [6, 5]

Matrix Multiplication
Two matrices can be multiplied together if the number of columns in the first matrix is equal to the number of rows in the second matrix. The product of two matrices is a new matrix whose elements are the dot products of the rows of the first matrix and the columns of the second matrix

In [ ]:
from numpy import array
# Transformation 1
i_hat1 = array([0, 1])
j_hat1 = array([-1, 0])
transform1 = array([i_hat1, j_hat1]).transpose()
# Transformation 2
i_hat2 = array([1, 0])
j_hat2 = array([1, 1])
transform2 = array([i_hat2, j_hat2]).transpose()
# Combine Transformations
combined = transform2 @ transform1
# Test
print("COMBINED MATRIX:\n {}".format(combined))
v = array([1, 2])
print(combined.dot(v)) # [-1, 1]

In [ ]:
from numpy import array
# Transformation 1
i_hat1 = array([0, 1])
j_hat1 = array([-1, 0])
transform1 = array([i_hat1, j_hat1]).transpose()
# Transformation 2
i_hat2 = array([1, 0])
j_hat2 = array([1, 1])
transform2 = array([i_hat2, j_hat2]).transpose()
# Combine Transformations, apply sheer first and then rotation
combined = transform1 @ transform2
# Test
print("COMBINED MATRIX:\n {}".format(combined))
v = array([1, 2])
print(combined.dot(v)) # [-2, 3]

Determinants
The determinant of a square matrix is a scalar value that can be computed from its elements. The determinant of a 2x2 matrix [a, b; c, d] is ad - bc. The determinant of a 3x3 matrix can be computed using the rule of Sarrus.


In [ ]:
from numpy.linalg import det
from numpy import array
i_hat = array([3, 0])
j_hat = array([0, 2])
basis = array([i_hat, j_hat]).transpose()
determinant = det(basis)
print(determinant) # prints 6.0

In [ ]:
from numpy.linalg import det
from numpy import array
i_hat = array([1, 0])
j_hat = array([1, 1])
basis = array([i_hat, j_hat]).transpose()
determinant = det(basis)
print(determinant) # prints 1.0

In [ ]:
from numpy.linalg import det
from numpy import array
i_hat = array([-2, 1])
j_hat = array([1, 2])
basis = array([i_hat, j_hat]).transpose()
determinant = det(basis)
print(determinant) # prints -5.0

In [ ]:
from numpy.linalg import det
from numpy import array
i_hat = array([-2, 1])
j_hat = array([3, -1.5])
basis = array([i_hat, j_hat]).transpose()
determinant = det(basis)
print(determinant) # prints 0.0

Special Types of Matrices
There are a few notable cases of matrices that we should cover.
Square Matrix
The square matrix is a matrix that has an equal number of rows and columns:
4 2 7
5 1 9
4 0 1
They are primarily used to represent linear transformations and are a requirement for
many operations like eigendecomposition.
Identity Matrix
The identity matrix is a square matrix that has a diagonal of 1s while the other values
are 0:
1 0 0
0 1 0
0 0 1
What’s the big deal with identity matrices? Well, when you have an identity matrix,
you essentially have undone a transformation and found your starting basis vectors.
This will play a big role in solving systems of equations in the next section.
Inverse Matrix
An inverse matrix is a matrix that undoes the transformation of another matrix. Let’s
say I have matrix A
Diagonal Matrix
Similar to the identity matrix is the diagonal matrix, which has a diagonal of nonzero
values while the rest of the values are 0. Diagonal matrices are desirable in certain
computations because they represent simple scalars being applied to a vector space. It
shows up in some linear algebra operations.
4 0 0
0 2 0
0 0 5
Triangular Matrix
Similar to the diagonal matrix is the triangular matrix, which has a diagonal of
nonzero values in front of a triangle of values, while the rest of the values are 0.
4 2 9
0 1 6
0 0 5
Triangular matrices are desirable in many numerical analysis tasks, because they
typically are easier to solve in systems of equations. They also show up in certain
decomposition tasks like LU Decomposition.
Sparse Matrix
Occasionally, you will run into matrices that are mostly zeroes and have very few
nonzero elements. These are called sparse matrices. From a pure mathematical
standpoint, they are not terribly interesting. But from a computing standpoint, they
provide opportunities to create efficiency. If a matrix has mostly 0s, a sparse matrix
implementation will not waste space storing a bunch of 0s, and instead only keep
track of the cells that are nonzero.
sparse:
0 0 0
0 0 2
0 0 0
0 0 0
When you have large matrices that are sparse, you might explicitly use a sparse
function to create your matrix.

Systems of Equations and Inverse Matrices
One of the most common applications of linear algebra is solving systems of
equations. A system of equations is a collection of equations that you solve
simultaneously. For example, consider the following system of equations:
2x + 3y = 8
4x + 5y = 18
This system of equations can be represented as a matrix equation Ax = b, where A is
the matrix of coefficients, x is the vector of variables, and b is the vector of constants.
To solve this system of equations, we can use the inverse of the matrix A. The inverse
of a matrix A is denoted as A^-1 and has the property that A * A^-1 = I, where I is the
identity matrix. To solve the system of equations Ax = b, we can multiply both sides by
the inverse of A to get x = A^-1 * b.

In [ ]:
from sympy import *
# 4x + 2y + 4z = 44
# 5x + 3y + 7z = 56
# 9x + 3y + 6z = 72
A = Matrix([
[4, 2, 4],
[5, 3, 7],
[9, 3, 6]
])
# dot product between A and its inverse
# will produce identity function
inverse = A.inv()
identity = inverse * A
# prints Matrix([[-1/2, 0, 1/3], [11/2, -2, -4/3], [-2, 1, 1/3]])
print("INVERSE: {}".format(inverse))
# prints Matrix([[1, 0, 0], [0, 1, 0], [0, 0, 1]])
print("IDENTITY: {}".format(identity))

In [ ]:
from numpy import array
from numpy.linalg import inv
# 4x + 2y + 4z = 44
# 5x + 3y + 7z = 56
# 9x + 3y + 6z = 72
A = array([
[4, 2, 4],
[5, 3, 7],
[9, 3, 6]
])
B = array([
44,
56,
72
])
X = inv(A).dot(B)
print(X) # [ 2. 34. -8.]

In [ ]:
from sympy import *
# 4x + 2y + 4z = 44
# 5x + 3y + 7z = 56
# 9x + 3y + 6z = 72
A = Matrix([
[4, 2, 4],
[5, 3, 7],
[9, 3, 6]
])
B = Matrix([
44,
56,
72
)
X = A.inv() * B
print(X) # Matrix([[2], [34], [-8]])

In [ ]:
rom numpy import array, diag
from numpy.linalg import eig, inv
A = array([
[1, 2],
[4, 5]
])
eigenvals, eigenvecs = eig(A)
print("EIGENVALUES")
print(eigenvals)
print("\nEIGENVECTORS")
print(eigenvecs)
"""
EIGENVALUES
[-0.46410162 6.46410162]
EIGENVECTORS
[[-0.80689822 -0.34372377]
[ 0.59069049 -0.9390708 ]]

In [ ]:
from numpy import array, diag
from numpy.linalg import eig, inv
A = array([
[1, 2],
[4, 5]
])
eigenvals, eigenvecs = eig(A)
print("EIGENVALUES")
print(eigenvals)
print("\nEIGENVECTORS")
print(eigenvecs)
print("\nREBUILD MATRIX")
Q = eigenvecs
R = inv(Q)
L = diag(eigenvals)
B = Q @ L @ R
print(B)